version: '3'

services:

  mev-boost:
    image: flashbots/mev-boost:${VERSION:-1.7}
    networks:
      - eth-network
    ports:
      - "${PORT_MEV:-18550}:${PORT_MEV:-18550}"
    command: |
      -${NETWORK:-holesky}
      -loglevel=info
      -addr=0.0.0.0:${PORT_MEV:-18550}
      -relay-check
      -relays=${MEVBOOST_RELAYS:-"https://0xaa58208899c6105603b74396734a6263cc7d947f444f396a90f7b7d3e65d102aec7e5e5291b27e08d02c50a050825c2f@holesky.titanrelay.xyz,https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-holesky.flashbots.net,https://0xab78bf8c781c58078c3beb5710c57940874dd96aef2835e7742c866b4c7c0406754376c2c8285a36c630346aa5c5f833@holesky.aestus.live"}
    restart: unless-stopped

networks:
  eth-network:
    name: ${NET_NAME}
    driver: bridge
    ipam:
      config:
        - subnet: ${NET_CIDR}
          gateway: ${NET_GATEWAY}
